apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: storage-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports/jenkins/
            name: vol-jenkins
          - mountPath: /exports/artifactory/
            name: vol-artifactory
      volumes:
        - name: vol-jenkins
          persistentVolumeClaim:
            claimName: vclm-jenkins
        - name: vol-artifactory
          persistentVolumeClaim:
            claimName: vclm-artifactory
