apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vclm-jenkins
  namespace: storage-nfs
spec:
  volumeName: pv-jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vclm-artifactory
  namespace: storage-nfs
spec:
  volumeName: pv-artifactory
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
