apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  namespace: storage-nfs
  labels:
    type: nfs
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  gcePersistentDisk:
    pdName: dsk-jenkins
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-artifactory
  namespace: storage-nfs
  labels:
    type: nfs
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  gcePersistentDisk:
    pdName: dsk-artifactory
    fsType: ext4
