apiVersion: v1
kind: PersistentVolume
metadata:
 name: vol-storage
spec:
 capacity:
   storage: 100G
 accessModes:
   - ReadWriteMany
 nfs:
   path: /containers/
   server: 10.157.195.154

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: fileserver
spec:
    accessModes:
    - ReadWriteMany      
    resources:
        requests:
          storage: 100G