apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: produccion-publico
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: gcr.io/potent-howl-286200/web
          ports:
            - containerPort: 80
              protocol: TCP
---
  
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: produccion-publico
spec:
  selector:
    app: proxy
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 34.107.198.246
status:
    loadBalancer:
      ingress:
      - ip: 34.107.198.246
