apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-infra
  labels:
    pool: lb-pl-infra
spec:
  storageClassName: azureFile
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 500Gi
  azureFile:
    secretName: infra
    shareName: infra
