apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gcr.io/potent-howl-286200/web
          ports:
            - containerPort: 80
              protocol: TCP
---
  
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
status:
    loadBalancer:
      ingress:
      - ip: 35.193.39.194
